version: "3.8"

services:
  serverd:
    build:
      context: .
      dockerfile: Dockerfile.serverd.dev
    ports:
      - 8081:8081
    environment:
      PORT: "8081"
    volumes:
      - ./:/app
